title: >
  <div style="text-align: center;">
    Teko Ntimane
    <br>
    <span style="font-size: 14px;"><em>Moderator, Speaker, Mentor</em></span>
  </div>
logo: /assets/img/headshot_circle.jpg
description: >
  <a href="https://www.linkedin.com/in/example/" style="display: block; text-align: center; font-size: 13px;">
    View My LinkedIn Profile
  </a>
  <div style="text-align: center;"><h3>Achievements</h3></div>
  <div style="max-height: 250px; overflow-y: scroll; font-size: 12px; scrollbar-width: none; -ms-overflow-style: none;">
    <style>
      /* Hide scrollbar for Webkit browsers */
      div::-webkit-scrollbar {
        display: none;
      }
    </style>
    <strong>Tech4Dev Moderator, Speaker & Mentor:</strong>
    <a>Empowering women and girls across Africa with digital skills and work readiness.</a>
    <a href="https://example.com/tech4dev">Learn more</a>
    <br><br>
    <strong>Youth Ambassador:</strong> 
    <a>Women In Tech South African Youth Ambassador and 2x winner for Digital & Social Impact (Paris, France).</a>
    <a href="https://example.com/youth-ambassador">Learn more</a>
    <br><br>
    <strong>Global Program Coordinator:</strong> 
    <a>Co-launched Women In Tech Global Mentorship, connecting 200+ mentors with 1,000+ mentees.</a>
    <a href="https://example.com/global-program-coordinator">Learn more</a>
    <br><br>
    <strong>Program Pioneer:</strong> 
    <a>Launched Sanlam's Data & Digital Academy experience week, providing practical experience to students.</a>
    <a href="https://example.com/program-pioneer">Learn more</a>
    <br><br>
    <strong>Founder & Campaign Champion:</strong> 
    <a>Raised R16,000+ by founding End.ometriosis and running 21km for menstrual health awareness.</a>
    <a href="https://example.com/endometriosis-campaign">Learn more</a>
    <br><br>
  </div>
theme: jekyll-theme-minimal
