title: Teko Ntimane
logo: /assets/img/headshot_circle.jpg
description: >
  Moderator, Speaker, Mentor 
  <div style="max-height: 150px; overflow-y: scroll; font-size: 12px; scrollbar-width: none; -ms-overflow-style: none;">
    <style>
      /* Hide scrollbar for Webkit browsers */
      div::-webkit-scrollbar {
        display: none;
      }
    </style>
    <br><br>
    <h3>Achievements</h3>
    <ul>
      <li>
        <strong>Tech4Dev Moderator, Speaker & Mentor:</strong> Empowering women and girls across Africa with digital skills and work readiness. 
        <a href="https://example.com/tech4dev">Learn more</a>
      </li>
      <li>
        <strong>Youth Ambassador:</strong> Women In Tech South African Youth Ambassador and 2x winner for Digital & Social Impact (Paris, France). 
        <a href="https://example.com/youth-ambassador">Learn more</a>
      </li>
      <li>
        <strong>Global Program Coordinator:</strong> Co-launched Women In Tech Global Mentorship, connecting 200+ mentors with 1,000+ mentees. 
        <a href="https://example.com/global-program-coordinator">Learn more</a>
      </li>
      <li>
        <strong>Program Pioneer:</strong> Launched Sanlam's Data & Digital Academy experience week, providing practical experience to students. 
        <a href="https://example.com/program-pioneer">Learn more</a>
      </li>
      <li>
        <strong>Founder & Campaign Champion:</strong> Raised R16,000+ by founding End.ometriosis and running 21km for menstrual health awareness. 
        <a href="https://example.com/endometriosis-campaign">Learn more</a>
      </li>
    </ul>
    <br><br>
    <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  </div>
theme: jekyll-theme-minimal

  
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme

  # - title: Tech4Dev Moderator, Speaker & Mentor
  #   description: Empowering women and girls across Africa with digital skills and work readiness.
  #   link: "https://example.com/tech4dev"

  # - title: Youth Ambassador
  #   description: Women In Tech South African Youth Ambassador and 2x winner for Digital & Social Impact (Paris, France).
  #   link: "https://example.com/youth-ambassador"

  # - title: Global Program Coordinator
  #   description: Co-launched Women In Tech Global Mentorship, connecting 200+ mentors with 1,000+ mentees.
  #   link: "https://example.com/global-program-coordinator"

  # - title: Program Pioneer
  #   description: Launched Sanlam's Data & Digital Academy experience week, providing practical experience to students.
  #   link: "https://example.com/program-pioneer"

  # - title: Founder & Campaign Champion
  #   description: Raised R16,000+ by founding End.ometriosis and running 21km for menstrual health awareness.
  #   link: "https://example.com/endometriosis-campaign"
