title: >
  <div style="text-align: center;">Teko Ntimane</div>
logo: /assets/img/headshot_circle.jpg
description: >
  Moderator, Speaker, Mentor 
  <h3>Achievements</h3>
  <div style="max-height: 300px; overflow-y: scroll; font-size: 12px; scrollbar-width: none; -ms-overflow-style: none;">
    <style>
      /* Hide scrollbar for Webkit browsers */
      div::-webkit-scrollbar {
        display: none;
      }
    </style>
    <strong>Tech4Dev Moderator, Speaker & Mentor:</strong> Empowering women and girls across Africa with digital skills and work readiness. 
    <a href="https://example.com/tech4dev">Learn more</a>
    <br><br>
    <strong>Youth Ambassador:</strong> Women In Tech South African Youth Ambassador and 2x winner for Digital & Social Impact (Paris, France). 
    <a href="https://example.com/youth-ambassador">Learn more</a>
    <br><br>
    <strong>Global Program Coordinator:</strong> Co-launched Women In Tech Global Mentorship, connecting 200+ mentors with 1,000+ mentees. 
    <a href="https://example.com/global-program-coordinator">Learn more</a>
    <br><br>
    <strong>Program Pioneer:</strong> Launched Sanlam's Data & Digital Academy experience week, providing practical experience to students. 
    <a href="https://example.com/program-pioneer">Learn more</a>
    <br><br>
    <strong>Founder & Campaign Champion:</strong> Raised R16,000+ by founding End.ometriosis and running 21km for menstrual health awareness. 
    <a href="https://example.com/endometriosis-campaign">Learn more</a>
    <br><br>
    <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  </div>
theme: jekyll-theme-minimal
